title: "Dickson Li"
url: "https://dicksonli.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Adapted from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Hello"
   link: "/researcher/"
 - name: "Test"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Projects"
   link: "contact"
